### ISSUE TITLE
New Video: Handmade Hero Day 035 - Basic Sparse Tilemap Storage

### ISSUE THREAD

**Issue by bnwasteland** [HandmadeCompanion/HandmadeCompanion#32]
Handmade Hero Day 035 - Basic Sparse Tilemap Storage<br>
http://ift.tt/1ygTyrN<br><div style="color: #000000; font-family: Arial, Helvetica, sans-serif; font-size: 12px; font-size: 12px; width: 555px;">
<table cellspacing="0" cellpadding="0" border="0"><tbody>
<tr>
<td width="140" valign="top" rowspan="2">
<div style="margin: 0px 10px 5px 0px;"><a href="http://ift.tt/1ygTyrN"><img alt="" src="http://ift.tt/1BpIiXI"></a></div>
</td>
<td width="256" valign="top">
<div style="font-size: 12px; font-weight: bold;">
<a style="font-size: 15px; font-weight: bold;" href="http://ift.tt/1ygTyrN">Handmade Hero Day 035 - Basic Sparse Tilemap Storage</a><br>
</div>
<div style="font-size: 12px; margin: 3px 0px;"><span>Day 035 of coding on Handmade Hero. See http://handmadehero.org for details.</span></div>
</td>
<td style="font-size: 11px; line-height: 1.4em; padding-left: 20px; padding-top: 1px;" width="146" valign="top">
<div>
<span style="color: #666666; font-size: 11px;">From:</span> <a href="http://ift.tt/13k8nMC">Handmade Hero</a>
</div>
<div>
<span style="color: #666666; font-size: 11px;">Views:</span> 0</div>
<div style="white-space: nowrap; text-align: left;">
<img style="margin: 0px; padding: 0px; vertical-align: middle; font-size: 11px;" align="top" alt="" src="http://ift.tt/iBDJTS"><img style="margin: 0px; padding: 0px; vertical-align: middle; font-size: 11px;" align="top" alt="" src="http://ift.tt/iBDJTS"><img style="margin: 0px; padding: 0px; vertical-align: middle; font-size: 11px;" align="top" alt="" src="http://ift.tt/iBDJTS"><img style="margin: 0px; padding: 0px; vertical-align: middle; font-size: 11px;" align="top" alt="" src="http://ift.tt/iBDJTS"><img style="margin: 0px; padding: 0px; vertical-align: middle; font-size: 11px;" align="top" alt="" src="http://ift.tt/iBDJTS">
</div>
<div style="font-size: 11px;">0 <span style="color: #666666; font-size: 11px;">ratings</span>
</div>
</td>
</tr>
<tr>
<td>
<span style="color: #666666; font-size: 11px;">Time:</span> <span style="color: #000000; font-size: 11px; font-weight: bold;">01:47:47</span>
</td>
<td style="font-size: 11px; padding-left: 20px;">
<span style="color: #666666; font-size: 11px;">More in</span> <a href="http://ift.tt/tGpe6o">Education</a>
</td>
</tr>
</tbody></table>
</div>
<br><br>
via Uploads by Handmade Hero http://ift.tt/1zFBcjl<br>
January 02, 2015 at 04:15PM

**Comment by abnercoimbre** [comment]
Added timestamp for Day035, thanks to @cfedor-git

**Comment by schme** [comment]
Oh wow. I actually had these and I thought I pushed them, but apparently forgot to do the ACTUAL PUSH. Good job me. Sorry for the extra work caused to cfedor. Won't happen again..

**Comment by cfedor-git** [comment]
I did several text summaries and only did timestamps in them as reference - they were not meant to be the full time stamp list. More importantly I did not do any of the Q&A timestamps. I think having those in the time stamps is excellent - so that work is still out there.

Not sure if abner will add in the summaries or I may eventually get to it.

I am new to all this git stuff - once I get with the program - i'll try to coordinate some. Feel free to edit anything I put together.

**Comment by schme** [comment]
Apparently my mistake wasn't the lack of push, but a lack of commit. So I just overwrote my notes, including the Q&A which I could've added. Teaches me to be more careful. So I'll probably leave that untouched for now. Anyway, thanks for contributing! Small text summaries are more or less what we've been doing anyway ;)

**Comment by cfedor-git** [comment]
My text summaries are getting large - more like a few pages (3-4 depending on examples). I wanted something that I could just read if I didn't have time to watch the videos - or re-read to get a quick refresher.

**Comment by abnercoimbre** [comment]
I did not add the summaries precisely because we need to discuss formatting, given that you have added example code in most of them. It's also more involved to proofread large summaries and make corrections.

I have contacted Casey et al. to discuss general instructions for uploading summaries. Once the instructions are up, we'll add your valuable contributions promptly. In the mean time, timestamps are a priority, and your unofficial ones for Day034 and Day035 were OK.

**Comment by abnercoimbre** [comment]
We're missing Q&A timestamps.

**Comment by dspecht** [comment]
We still need Q&A timestamps for the new people

**Comment by abnercoimbre** [comment]
Completed Day 35.
